name: "Bazel buildifier"
description: "Run buildifier on bazel BUILD files in a code base"
author: "Joshua Thompson"
branding:
  icon: "award"
  color: "purple"
inputs:
  filetypes:
    description: "Comma separated list of bazel BUILD files to"
    required: false
  excludes:
    description: "Exclude paths to pass to find's -path arg"
    required: false
  warnings:
    description: "Set of warnings to include or exclude"
    required: false
  buildifier_version:
    description: "Version of buildifier to use"
    required: false
    default: 4.0.1
runs:
  using: "docker"
  image: "Dockerfile"
